### ISSUE TITLE
How to load data in the list

### ISSUE THREAD

**Issue by lwxzks** [ashrithks/rn-collapsing-tab-bar#13]

**Comment by ashrithks** [comment]
Need more detail

**Comment by lwxzks** [comment]
> Need more detail
Flatlist can't load data in rn-collapsing-tab-bar , Cannot trigger onEndReached

**Comment by xuho** [comment]
> > Need more detail
> > Flatlist can't load data in rn-collapsing-tab-bar , Cannot trigger onEndReached

https://github.com/ashrithks/rn-collapsing-tab-bar/issues/1
Using loadMore props of ScrollableTabView, set scrollEnabled={false} to Flatlist.

**Comment by lwxzks** [comment]
> > > Need more detail
> > > Flatlist can't load data in rn-collapsing-tab-bar , Cannot trigger onEndReached
> 
> #1
> Using loadMore props of ScrollableTabView, set scrollEnabled={false} to Flatlist.

ScrollableTabView which method can loadMore

**Comment by lwxzks** [comment]
> > > Need more detail
> > > Flatlist can't load data in rn-collapsing-tab-bar , Cannot trigger onEndReached
> 
> #1
> Using loadMore props of ScrollableTabView, set scrollEnabled={false} to Flatlist.

ScrollableTabView which method can loadMore ？

**Comment by ashrithks** [comment]
loadMore method, send according to tabs

**Comment by lwxzks** [comment]
> loadMore方法，根据选项卡发送

react-native-scrollable-tab-view  Which method to slide to the bottom？Please explain the white point
