### ISSUE TITLE
Swipe and status bar issue

### ISSUE THREAD

**Issue by Jalson1982** [ashrithks/rn-collapsing-tab-bar#3]
Hello.  This works very nice. Have two questions.
1. How to include status bar?
2. When start swipe it shows background color not content of react component i want to swipe. Any chance to fix it?
Cheers.

**Comment by ashrithks** [comment]
https://github.com/benevbright/react-navigation-collapsible

**Comment by ashrithks** [comment]
https://github.com/benevbright/react-navigation-collapsible
@Jalson1982

**Comment by Jalson1982** [comment]
it has more issues then your solution hehe

**Comment by ashrithks** [comment]
There is a prop to render, prerenderingSiblingsNumber
Because of collapsing toolbarits not working

**Comment by Jalson1982** [comment]
So prerenderingSiblingsNumber can not use to have both components render and avoid white screen when swipe?

**Comment by ashrithks** [comment]
Hello,
Native base has introduced this feature,
https://codeburst.io/react-native-parallax-scroll-with-tabs-721feec463c5
https://medium.com/@andi.gu.ca/a-collapsing-navbar-with-tabs-in-react-native-e80790588830

**Comment by ashrithks** [comment]
https://github.com/GeekyAnts/NativeBase/tree/master/src/basic/Tabs,
