### ISSUE TITLE
Tab content re-rendering when change tab

### ISSUE THREAD

**Issue by xuho** [ashrithks/rn-collapsing-tab-bar#6]
I see when i change to new tab, the content in this tab will re-rendering again?
Have any solution to fix it?
Thank.

**Comment by xuho** [comment]
@ashrithks please resolve this issue

**Comment by Albert0405** [comment]
same here, how to fix that?

**Comment by Albert0405** [comment]
@xuho  

I found a tutorial that does with `nativebase` tabs component. It doesn't re-render tabs. Try it
https://medium.com/@andi.gu.ca/a-collapsing-navbar-with-tabs-in-react-native-e80790588830

**Comment by ashrithks** [comment]
Hello,
Native base has introduced this feature,
https://codeburst.io/react-native-parallax-scroll-with-tabs-721feec463c5
https://medium.com/@andi.gu.ca/a-collapsing-navbar-with-tabs-in-react-native-e80790588830

**Comment by Albert0405** [comment]
@ashrithks Unfortunately there is a bug where the tab with a highest height will shared among other tabs as well. So let say Tab 1 has 1000 height and Tab 2 has 300 height only, when you use his approach, the Tab 2 will no longer have 300 height but 1000 height

**Comment by ashrithks** [comment]
in nativebase?

**Comment by ashrithks** [comment]
got this ,
https://snack.expo.io/@ashrithks/search-bar-animation

**Comment by Albert0405** [comment]
Yes

I've also used that lib before but you cant swipe the tabs plus switching tabs will automatically scroll to the top part of the tab not with the current y position where you left it. Try it, on Tab1 scroll to the bottom part then tap on Tab2 and go back to Tab1, you will see the Tab1 is in top position again

**Comment by ashrithks** [comment]
Fixed, Update to latest, 0.1.6
check , https://github.com/ashrithks/rn-collapsing-tab-bar/blob/master/Example/CollapseExample.js
for example @Albert0405 @xuho
