### ISSUE TITLE
Prevent re-rendering tabs

### ISSUE THREAD

**Issue by Albert0405** [ashrithks/rn-collapsing-tab-bar#7]
Why does it need to rerender tabs? I've use Nativebase and it doesnt re-render the tabs once you open it and then decided go back again. How to fix it

**Comment by Albert0405** [comment]
@ashrithks any fix to this please?

**Comment by Albert0405** [comment]
@ashrithks  yo~ please any update?

**Comment by ashrithks** [comment]
Hello,
Native base has introduced this feature,
https://codeburst.io/react-native-parallax-scroll-with-tabs-721feec463c5
https://medium.com/@andi.gu.ca/a-collapsing-navbar-with-tabs-in-react-native-e80790588830

**Comment by ashrithks** [comment]
Fixed, Update to latest, 0.1.6 
check , https://github.com/ashrithks/rn-collapsing-tab-bar/blob/master/Example/CollapseExample.js
for example
