### ISSUE TITLE
My tabs after collapsing are hiding header but i want them below header after collapsing .Any way to achieve that?

### ISSUE THREAD

**Issue by ShrutiGarg019** [ashrithks/rn-collapsing-tab-bar#8]

**Comment by ashrithks** [comment]
Hello,
Native base has introduced this feature,
https://codeburst.io/react-native-parallax-scroll-with-tabs-721feec463c5
https://medium.com/@andi.gu.ca/a-collapsing-navbar-with-tabs-in-react-native-e80790588830
